{{- if (and .Values.was.enabled .Values.was.secrets.create (eq .Values.was.secrets.type "cloud")) }}
kind: ExternalSecret
apiVersion: kubernetes-client.io/v1
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    tier: snowflake-was
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 -}}
    {{- end }}
  {{- with .Values.was.secrets.annotations}}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  backendType: secretsManager
  region: {{ .Values.was.secrets.spec.region }}
  data:
    {{- if .Values.was.secrets.spec.data }}
      {{- toYaml .Values.was.secrets.spec.data | nindent 6 }}
    {{- end }}
{{- else if (and .Values.was.enabled .Values.was.secrets.create (eq .Values.was.secrets.type "local")) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    tier: snowflake-was
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.was.secrets.annotations}}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.was.secrets.localData }}
    {{- range $i, $env := .Values.was.secrets.localData }}
  {{ $env.name }}: {{ $env.value | b64enc | quote }}
    {{- end }}  
  {{- end }}
{{- end }}
