{{- if and .Values.was.enabled .Values.was.serviceAccount.create }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "was.serviceAccountName" . }}
  labels:
    tier: snowflake-was
    component: was
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    {{- if or (.Values.labels) (.Values.was.labels) }}
      {{- mustMerge .Values.was.labels .Values.labels | toYaml | nindent 4 }}
    {{- end }}
  {{- with .Values.was.serviceAccount.annotations}}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
