name: Container CI for ghcr.io

on:
  release:
    types:
      - published

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Go SemVer Extraction
        run: |
          echo "GO_FULL_VER=$GITHUB_REF_NAME" >> $GITHUB_ENV
          GO_MINOR_VER=${GITHUB_REF_NAME%.*}
          echo "GO_MINOR_VER=$GO_MINOR_VER" >> $GITHUB_ENV
          GO_MAJOR_VER=${GO_MINOR_VER%.*}
          echo "GO_MAJOR_VER=$GO_MAJOR_VER" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: davionchai
          password: ${{ secrets.GHCR_ALL_ACCESS }}

      - name: Container building
        run: |
          echo "Creating snowflake-was container with tags: [${{ env.GO_MAJOR_VER }}, ${{ env.GO_MINOR_VER }}, ${{ env.GO_FULL_VER }}]"
          docker build \
            -t ghcr.io/davionchai/snowflake-was:latest \
            -t ghcr.io/davionchai/snowflake-was:${{ env.GO_FULL_VER }} \
            -t ghcr.io/davionchai/snowflake-was:${{ env.GO_MINOR_VER }} \
            -t ghcr.io/davionchai/snowflake-was:${{ env.GO_MAJOR_VER }} \
            --file ./build/Dockerfile .
          docker push ghcr.io/davionchai/snowflake-was --all-tags
